ALTER TABLE bdcongelada ADD COLUMN `cantidadSolicitada` VARCHAR (50) DEFAULT "0";
ALTER TABLE bdcomanda ADD COLUMN `cantidadSolicitada` VARCHAR (50) DEFAULT "0";
ALTER TABLE bdcomanda ADD COLUMN `idCongelada` VARCHAR (50) ;
ALTER TABLE bdcomanda ADD COLUMN `idComanda` VARCHAR (50) ;
ALTER TABLE bdPreCompraDetalle ADD COLUMN `plu` TINYINT (1) ;
UPDATE bdproductos SET Descripcion='GUARDERIA X DIA' WHERE Codigo='GD2';
UPDATE bdproductos SET Descripcion='GUARDERIA X HORA' WHERE Codigo='GD1';
DELETE FROM bdServiciosPTM;
DELETE FROM bdServiciosPTM1;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`click`@`localhost` SQL SECURITY DEFINER VIEW `impresioncomanda` AS SELECT `con`.`idFactura`     AS `idFactura`, `con`.`producto`      AS `producto`, `con`.`cantidad`      AS `cantidad`, `con`.`descripcion`   AS `descripcion`, `con`.`plu`           AS `plu`, `con`.`cant2`         AS `cant2`, `con`.`lista`         AS `lista`, `con`.`descuento`     AS `descuento`, `con`.`preparacion`   AS `preparacion`, `con`.`conseMesa`     AS `conseMesa`, `con`.`notaAnulacion` AS `notaAnulacion`, `con`.`rango`         AS `rango`, `con`.`porcDescuento` AS `porcDescuento`, `con`.`imei`          AS `imei`, `con`.`idProd`        AS `idProd`, `con`.`impoconsumo`   AS `impoconsumo`, `con`.`porcImpo`      AS `porcImpo`, `p`.`grupo`           AS `grupo`, `con`.`id`            AS `idComanda`, `con`.`cantidadSolicitada` AS `cantidadSolicitada` FROM (`bdcongelada` `con` JOIN `bdproductos` `p` ON (`p`.`idSistema` = `con`.`producto`))*/;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`click`@`localhost` SQL SECURITY DEFINER VIEW `productossinpreparacion` AS  SELECT `bdcomanda`.`Id`            AS `Id`, `bdcomanda`.`congelada`     AS `congelada`, `bdcomanda`.`factura`       AS `factura`, `bdcomanda`.`pedido`        AS `pedido`, `bdcomanda`.`cod`           AS `cod`, `bdcomanda`.`producto`      AS `producto`, `bdcomanda`.`opciones`      AS `opciones`, `bdcomanda`.`ingredientes`  AS `ingredientes`, `bdcomanda`.`aderezos`      AS `aderezos`, `bdcomanda`.`cant`          AS `cant`, `bdcomanda`.`observaciones` AS `observaciones`, `bdcomanda`.`consecutivo`   AS `consecutivo`, `bdcomanda`.`cantidadSolicitada`   AS `cantidadSolicitada` FROM `bdcomanda` WHERE `bdcomanda`.`opciones` = '' AND `bdcomanda`.`ingredientes` = '' AND `bdcomanda`.`aderezos` = '' AND `bdcomanda`.`observaciones` = '' */;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ajustessalida` AS ( SELECT `bdtraslados`.`Id` AS `Id`, `bdtraslados`.`tipo`         AS `tipo`, `bdtraslados`.`anulada`      AS `anulada`, `bdtrasladosprod`.`producto` AS `producto`, `bdtrasladosprod`.`cantidad` AS `cantidad`, `bdtrasladosprod`.`cantidad2` AS `cantidad2`, `bdtrasladosprod`.`lista`    AS `lista`, `bdtrasladosprod`.`total`    AS `total`, `bdtraslados`.`usuario`      AS `usuario`, `bdtraslados`.`fecha`        AS `fecha`, `bdtraslados`.`bodega`       AS `bodega` FROM (`bdtraslados` LEFT JOIN (`bdtrasladosprod` LEFT JOIN `bdproductos` ON (`bdtrasladosprod`.`producto` = `bdproductos`.`idSistema`)) ON (`bdtraslados`.`Id` = `bdtrasladosprod`.`traslado`)) WHERE `bdtraslados`.`tipo` = 'Ajuste Salida' AND `bdtraslados`.`anulada` = 0) */;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `totalizadoajustesalida` AS  SELECT `bdproductos`.`idSistema` AS `codigo`, SUM(IF(`ajustessalida`.`cantidad2` IS NULL,'0',`ajustessalida`.`cantidad2`)) AS `Expr1` FROM (`bdproductos` LEFT JOIN `ajustessalida` ON (`bdproductos`.`idSistema` = `ajustessalida`.`producto`)) WHERE `ajustessalida`.`bodega` = '123-22' OR `ajustessalida`.`bodega` = '' GROUP BY `bdproductos`.`idSistema` */;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `inventario` AS ( SELECT `bdproductos`.`idSistema` AS `Codigo`,`bdproductos`.`Descripcion` AS `Descripcion`,`bdproductos`.`inventario` AS `inventario`,CAST(`bdproductos`.`inventario` AS SIGNED) AS `inv`,`bdproductos`.`fisicoInventario` AS `fisicoInventario`,`bdproductos`.`compras` AS `compras`,`bdproductos`.`ventas` AS `ventas`,`bdproductos`.`nc` AS `nc`,`bdproductos`.`ajusteEntrada` AS `ajusteEntrada`,`bdproductos`.`ajusteSalida` AS `ajusteSalida`,`bdproductos`.`planSepare` AS `planSepare`,`bdproductos`.`pedidos` AS `pedidos`,`bdproductos`.`anulacion` AS `anulacion`,`bdproductos`.`inventarioInicial` AS `inventarioInicial`,`bdproductos`.`ajusteInventario` AS `ajusteInventario`,`bdproductos`.`armado` AS `armado`,`bdproductos`.`costeo` AS `costeo`,`ultimoponderado`.`nuevoPonderado` AS `costoUnd`,`ultimoponderado`.`ultimoCosto` AS `ultimoCosto`,`bdproductos`.`minimo` AS `minimo`,IF(CAST(`bdproductos`.`fisicoInventario` AS SIGNED) <= 0,'SIN INVENTARIO',IF(CAST(`bdproductos`.`fisicoInventario` AS SIGNED) < `bdproductos`.`minimo`,'BAJO',IF(CAST(`bdproductos`.`fisicoInventario` AS SIGNED) = `bdproductos`.`minimo`,'MEDIO','ALTO'))) AS `estado`,`bdproductos`.`L1` AS `L1`,`bdproductos`.`L2` AS `L2`,`bdproductos`.`referencia` AS `referencia`,`bdproductos`.`ubicacion1` AS `ubicacion1`,`bdgrupo`.`nombre` AS `grupoDesc`,`bdsubgrupo`.`nombre` AS `subGrupoDesc`,`bdterceros`.`nombre` AS `proveedorNombre`,`bdproductos`.`grupo` AS `Grupo`,CAST(REPLACE(`ultimoponderado`.`nuevoPonderado`,',','.') AS DOUBLE) * CAST(REPLACE(`bdproductos`.`inventario`,',','.') AS DOUBLE) AS `costoPTotal`,CAST(REPLACE(`ultimoponderado`.`ultimoCosto`,',','.') AS DOUBLE) * CAST(REPLACE(`bdproductos`.`inventario`,',','.') AS DOUBLE) AS `costoTotal`,`bdproductos`.`ordenServicio` AS `ordenServicio`,`bdproductos`.`manejaInventario` AS `manejaInventario`,`bdproductos`.`Proveedor` AS `Proveedor`,`ultimoponderado`.`fecha` AS `fecha`,`bdproductos`.`Codigo` AS `Codigo1`,`bdproductos`.`codigoBarras` AS `codigoBarras`,`bdproductos`.`trasladoInternoEntrada` AS `trasladoInternoEntrada`,`bdproductos`.`trasladoInternoSalida` AS `trasladoInternoSalida`,`bdproductos`.`congelada` AS `congelada`,`bdproductos`.`trasladoBod` AS `trasladoBod`,`bdproductos`.`enTransito` AS `enTransito`,`bdproductos`.`notaDebito` AS `nd` FROM ((((`bdproductos` LEFT JOIN `bdgrupo` ON(`bdgrupo`.`codigo` = `bdproductos`.`grupo`)) LEFT JOIN `bdsubgrupo` ON(`bdsubgrupo`.`codigo` = `bdproductos`.`Sub_grupo`)) LEFT JOIN `bdterceros` ON(`bdterceros`.`id` = `bdproductos`.`Proveedor`)) LEFT JOIN `ultimoponderado` ON(`ultimoponderado`.`producto` = `bdproductos`.`idSistema`))) */;

/*!50001 ALTER ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ajustesentrada` AS ( SELECT `bdtraslados`.`Id`           AS `Id`, `bdtraslados`.`tipo`         AS `tipo`, `bdtraslados`.`anulada`      AS `anulada`, `bdtrasladosprod`.`producto` AS `producto`, `bdtrasladosprod`.`cantidad` AS `cantidad`, `bdtrasladosprod`.`lista`    AS `lista`, `bdtrasladosprod`.`total`    AS `total`, `bdtraslados`.`fecha`        AS `fecha`, `bdtraslados`.`usuario`      AS `usuario`, `bdtraslados`.`bodega`       AS `bodega`, `bdtrasladosprod`.`cantidad2` AS `cantidad2` FROM (`bdtraslados` LEFT JOIN (`bdtrasladosprod` LEFT JOIN `bdproductos` ON (`bdtrasladosprod`.`producto` = `bdproductos`.`Codigo`)) ON (`bdtraslados`.`Id` = `bdtrasladosprod`.`traslado`)) WHERE `bdtraslados`.`tipo` = 'Ajustes Entrada' AND `bdtraslados`.`anulada` = 0) */;