/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios.Oftalmologia;

import clases.Instancias;
import clases.cambiarColorTabla;
import clases.metodosGenerales;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author .CLIK
 */
public class infReimpresionExamenes extends javax.swing.JFrame {

    Instancias instancias;
    metodosGenerales metodos;
    DefaultTableModel modelo;
    private Integer opc = null;
    private String nombre;

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public infReimpresionExamenes() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        this.setLocationRelativeTo(null);

//        jTable1.setDefaultRenderer(Object.class, new cambiarColorTabla(3));
    }

    public void setOpc(int opc) {
        this.opc = opc;
    }

    public metodosGenerales getMetodos() {
        return metodos;
    }

    public void setMetodos(metodosGenerales metodos) {
        this.metodos = metodos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Paciente:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            switch (jTable1.getToolTipText()) {
                case "formulaMedica":
                    this.dispose();
                    instancias.getFormulaMedicaOf().reimprimir(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    break;
                case "formLentes":
                    this.dispose();
                    String id = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                    instancias.getFormulaLentes().reimprimir(id);
                    break;
                case "ayudaDiagnostica":
                    this.dispose();
                    instancias.getAyudaDiagnosticoOf().reimprimir(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    break;
                case "incapacidad":
                    this.dispose();
                    instancias.getIncapacidadOf().reimprimir(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    break;
                case "biometria":
                    this.dispose();
                    instancias.getBiometria().reimprimir(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    break;
                case "paquimetria":
                    this.dispose();
                    instancias.getPaquimetria().reimprimir(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    break;
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infReimpresionExamenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infReimpresionExamenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infReimpresionExamenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infReimpresionExamenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infReimpresionExamenes().setVisible(true);
            }
        });
    }

    public void cargarRegistros(String paciente, String examen, Instancias instancias, String hist) {

        this.instancias = instancias;

        if (nombre != null) {
            jTextField2.setText(nombre);
        } else {
            jTextField2.setText(instancias.getSql().getDatosTercero(paciente).getNombre());
        }

        Object[][] datos = null;

        switch (examen) {
            case "formulaMedica":
                datos = instancias.getSql().getRegistrosExamens3(hist, "formulaMedicaOf");
                break;
            case "ayudaDiagnostica":
                modelo = new DefaultTableModel(datos, new Object[]{"Id", "Fecha", "Concepto"});
                jTable1.setModel(modelo);
                this.show();
                jTable1.setToolTipText(examen);
                datos = instancias.getSql().getRegistrosAyuda(hist, "conAyudaDiagnosticaOf");
                break;
            case "formLentes":
                datos = instancias.getSql().getRegistrosFormulaLentes(paciente, "formulaLentes");
                break;
            case "incapacidad":
                modelo = new DefaultTableModel(datos, new Object[]{"Id", "Fecha Inicio", "Fecha Vencimiento", "Descripcion"});
                jTable1.setModel(modelo);
                this.show();
                jTable1.setToolTipText(examen);
                datos = instancias.getSql().getRegistrosIncapacidad(hist, "bdIncapacidadOf");
                break;
            case "biometria":
                modelo = new DefaultTableModel(datos, new Object[]{"Id", "Fecha", "Cedula"});
                jTable1.setModel(modelo);
                this.show();
                jTable1.setToolTipText(examen);
                datos = instancias.getSql().getRegistrosBiometria(paciente, "bdBiometria");
                break;
            case "paquimetria":
                datos = instancias.getSql().getRegistrosPaquimetria(paciente, "bdPaquimetria");
                break;
        }

        for (Object[] dato : datos) {
            modelo.addRow(dato);
        }

        jTable1.setToolTipText(examen);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
